#!/bin/bash

if [ -z "$1" -o -z "$2" -o -z "$3" ]; then 
	echo "SYNTAX: $0 <isolation_id> <organization> <tag>"
else
	ISOLATION_ID=$1
	ORGANIZATION=$2
	TAG=$3
fi


for img in `docker images |grep ISOLATION_ID| awk '{print $1}'`; do
	docker tag $img:$ISOLATION_ID $ORGANIZATION/$img:$TAG
	docker push $ORGANIZATION/$img:$TAG
done
